IndBaTxt[6099]="Demi (buah) Tin dan (buah) Zaitun,";
IndBaTxt[6100]="dan demi bukit Sinai,";
IndBaTxt[6101]="dan demi kota (Mekah) ini yang aman,";
IndBaTxt[6102]="sesungguhnya Kami telah menciptakan manusia dalam bentuk yang sebaik-baiknya.";
IndBaTxt[6103]="Kemudian Kami kembalikan dia ke tempat yang serendah-rendahnya (neraka),";
IndBaTxt[6104]="kecuali orang-orang yang beriman dan mengerjakan amal saleh; maka bagi mereka pahala yang tiada putus-putusnya.";
IndBaTxt[6105]="Maka apakah yang menyebabkan kamu mendustakan (hari) pembalasan sesudah (adanya keterangan-keterangan) itu?";
IndBaTxt[6106]="Bukankah Allah Hakim yang seadil-adilnya?";
tloaded[95]['id.indonesian']=1;
