IndBaTxt[6169]="Bermegah-megahan telah melalaikan kamu,";
IndBaTxt[6170]="sampai kamu masuk ke dalam kubur.";
IndBaTxt[6171]="Janganlah begitu, kelak kamu akan mengetahui (akibat perbuatanmu itu),";
IndBaTxt[6172]="dan janganlah begitu, kelak kamu akan mengetahui.";
IndBaTxt[6173]="Janganlah begitu, jika kamu mengetahui dengan pengetahuan yang yakin,";
IndBaTxt[6174]="niscaya kamu benar-benar akan melihat neraka Jahiim,";
IndBaTxt[6175]="dan sesungguhnya kamu benar-benar akan melihatnya dengan 'ainul yaqin.";
IndBaTxt[6176]="kemudian kamu pasti akan ditanyai pada hari itu tentang kenikmatan (yang kamu megah-megahkan di dunia itu).";
tloaded[102]['id.indonesian']=1;
