IndBaTxt[6091]="Bukankah Kami telah melapangkan untukmu dadamu?,";
IndBaTxt[6092]="dan Kami telah menghilangkan daripadamu bebanmu,";
IndBaTxt[6093]="yang memberatkan punggungmu?";
IndBaTxt[6094]="Dan Kami tinggikan bagimu sebutan (nama)mu,";
IndBaTxt[6095]="Karena sesungguhnya sesudah kesulitan itu ada kemudahan,";
IndBaTxt[6096]="sesungguhnya sesudah kesulitan itu ada kemudahan.";
IndBaTxt[6097]="Maka apabila kamu telah selesai (dari sesuatu urusan), kerjakanlah dengan sungguh-sungguh (urusan) yang lain,";
IndBaTxt[6098]="dan hanya kepada Tuhanmulah hendaknya kamu berharap.";
tloaded[94]['id.indonesian']=1;
